### ISSUE TITLE
TypeError: ('object.__new__(SlideshowDescriptor) is not safe

### ISSUE THREAD

**Issue by sif77** [collective/collective.easyslideshow#22]
In Plone, i uninstalled collective.easyslideshow and i removed it from buildout.

After restart, i got 

```
2016-06-23T12:15:48 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/usr/local/plone/plone-4.3.9/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in __init__
    response=b)
  File "/usr/local/plone/plone-4.3.9/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/usr/local/plone/plone-4.3.9/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/usr/local/plone/plone-4.3.9/buildout-cache/eggs/Zope2-2.13.24-py2.7.egg/ZPublisher/BaseRequest.py", line 220, in close
    notify(EndRequestEvent(None, self))
  File "/usr/local/plone/plone-4.3.9/buildout-cache/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/usr/local/plone/plone-4.3.9/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/usr/local/plone/plone-4.3.9/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/usr/local/plone/plone-4.3.9/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/usr/local/plone/plone-4.3.9/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/Connection.py", line 914, in _setstate
    self._reader.setGhostState(obj, p)
  File "/usr/local/plone/plone-4.3.9/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/serialize.py", line 612, in setGhostState
    state = self.getState(pickle)
  File "/usr/local/plone/plone-4.3.9/buildout-cache/eggs/ZODB3-3.10.5-py2.7-linux-x86_64.egg/ZODB/serialize.py", line 605, in getState
    return unpickler.load()
  File "/usr/local/plone/plone-4.3.9/Python-2.7/lib/python2.7/copy_reg.py", line 48, in _reconstructor
    obj = object.__new__(cls)
TypeError: ('object.__new__(SlideshowDescriptor) is not safe, use Persistence.Persistent.__new__()', <function _reconstructor at 0x7f3247667a28>, (<class 'collective.easyslideshow.descriptors.SlideshowDescriptor'>, <type 'object'>, None))
------
2016-06-23T12:15:50 ERROR ZODB.Connection Shouldn't load state for 0x15 when the connection is closed

```

**Comment by cdw9** [comment]
Hi @sif77 - I just released easyslideshow version 2.3 last night, and it takes care of removing the persistent utilities. You would need to upgrade to 2.3 before removing it from the buildout.

I'm closing the issue since it should now be fixed, but please reopen if you have any more issues
